### ISSUE TITLE
Damaged zip archive

### ISSUE THREAD

**Issue by shojint** [HMS97/EVD4UAV#1]
I can't extract the zip file on the google drive. 

Error message met when trying to extract the zip file:
There was an error while extracting "EVD4UAV_DATASET.zip".
Damaged Zip archive

Does anyone know what the issue is? Thank you.

**Comment by HMS97** [comment]
Sorry for the damaged file. I will update soon, try one hour later.

**Comment by HMS97** [comment]
Done, you can try to download right now.

**Comment by shojint** [comment]
Thank you.
