### ISSUE TITLE
Showing "Damaged zip archive"

### ISSUE THREAD

**Issue by ERYAGNIK003** [HMS97/EVD4UAV#2]
After downloading ZIP, error is showing "damaged zip".

**Comment by HMS97** [comment]
Hi there, thanks for pointing out this problem, it's due to the window and mac zip format issue. Now, I have uploaded a 7z version link. You can download it now.

**Comment by ERYAGNIK003** [comment]
Thanks for prompt response. I got the working link. Thanks.
